<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AutoCADInstallDir Condition="'$(AutoCADInstallDir)' == ''">C:\Program Files\Autodesk\AutoCAD 2025</AutoCADInstallDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcCoreMgd" HintPath="$(AutoCADInstallDir)\AcCoreMgd.dll" Private="false" />
    <Reference Include="AcDbMgd" HintPath="$(AutoCADInstallDir)\AcDbMgd.dll" Private="false" />
    <Reference Include="AcMgd" HintPath="$(AutoCADInstallDir)\AcMgd.dll" Private="false" />
  </ItemGroup>
</Project>
