"""EXPERIMENTAL — NOT AUTHORIZED FOR PRODUCTION. I-62 night order §10: precision of the B.11 manifest on small real closures.

Not a re-issue of NDC-01 (closure sizes and incompleteness). This measures something new: edge PRECISION. On an EXPERIMENTAL COPY of the F3 manifest
(regenerated byte-for-byte equivalent by gen-manifest.py; the approved manifest is not modified) a few edges of real V14 units are labelled by reading
their text:
  CONTROL      the unit's normative content depends on the target (followed);
  INFORMATIVE  a pointer or a test reference; the unit's content does not depend on it (not followed in the copy: excess edge in the original);
  AMBIGUOUS    a legitimate ambiguity the generator already fails closed on (kept: Complete stays false);
  MISSING      a control dependency the text expresses by NAME, without a section reference, so the generator emits no edge (added in the copy).
Complete is never set to true. For each example the closure is computed on the original and on the copy, and the premise-crediting rule of §20.3.3
(credible only if every unit of the closure is Complete) is evaluated on both.

A second measurement counts, over the whole Proposal, the lines that name one of the 14 checks of AUTOMATION_PLAN 16.9 in backticks: the manifest has
no unit for 16.9 at all, so every such mention is a CANDIDATE missing control edge (approximate, by section; for the Architect review of B.11).

Usage: python b11_precision.py <manifest.json> <V14 text file> <out.json>
"""
import collections
import json
import re
import sys

MANIFEST, V14, OUT = sys.argv[1:4]
M = json.load(open(MANIFEST, encoding="utf-8"))
DOC = "docs/initiatives/I-62-proposal-v14.md"
AP = "docs/AUTOMATION_PLAN.md"
key = lambda d, u: d + "|" + u
E = {key(e["Source"]["Document"], e["Source"]["UnitId"]): e for e in M["Entries"]}

# labels (V14 commit 4c617e82, line numbers of the frozen text)
LABELS = [
    {"Unit": "§8.4#p1", "Target": key(DOC, "B.8.3"), "Label": "INFORMATIVE", "Line": 382,
     "Text": "«Tabla completa en B.8.3.»", "Why": "puntero desde un resumen; la unidad no tiene contenido normativo propio que dependa de la tabla"},
    {"Unit": "B.3#p1", "Target": key(DOC, "C-08"), "Label": "INFORMATIVE", "Line": 1849,
     "Text": "«… valida sin tocar el núcleo (C-08).»", "Why": "nombra la obligación que lo prueba; la regla no depende de C-08 (cierra el ciclo B.3 → B.3#p1 → C-08 → B.3)"},
    {"Unit": "§8.5#row6", "Target": key(DOC, "T10"), "Label": "CONTROL", "Line": 416,
     "Text": "«no fast-forward (el remoto avanzó) | `fetch` y clasificar según T10»", "Why": "el tratamiento lo define T10"},
    {"Unit": "C-08", "Target": key(DOC, "B.3"), "Label": "CONTROL", "Line": 2345,
     "Text": "«B.3: (a) adapter `test-null` …»", "Why": "la obligación prueba las reglas de B.3"},
    {"Unit": "§8.5#row4", "Target": None, "Label": "AMBIGUOUS", "Line": 405,
     "Text": "«… (16.1, sin cambio)»", "Why": "«16.1» sin documento: V14 no tiene 16.1 y §3.1 no lo mapea; el generador ya lo deja Complete = false (regla R5), y su resolución correcta (AUTOMATION_PLAN 16.1) sería externa e incompleta: UNKNOWN igual"},
    {"Unit": "§8.5#p1", "Target": key(AP, "16.9#5 Identity"), "Label": "MISSING", "Line": 408,
     "Text": "«`Identity` (`HEAD` = remoto = `CurrentSha`) **no cambia**.»",
     "Why": "afirma la vigencia de la comprobación 16.9 #5 por su NOMBRE; sin referencia de sección no hay arista y la unidad queda Complete con clausura {sí misma}"},
]


def closure(start, entries, extra, skip):
    seen, q, unknown = [start], [start], []
    while q:
        k = q.pop(0)
        e = entries.get(k)
        if e is None or not e["Complete"]:
            unknown.append(k)
        if e is None:
            continue
        targets = [key(d["Target"]["Unit"]["Document"], d["Target"]["Unit"]["UnitId"]) for d in e["DependsOn"] if d["Target"]["Kind"] == "UNIT"]
        targets = [t for t in targets if (k, t) not in skip] + extra.get(k, [])
        for t in targets:
            if t not in seen:
                seen.append(t)
                q.append(t)
    return seen, unknown


skip = {(key(DOC, l["Unit"]), l["Target"]) for l in LABELS if l["Label"] == "INFORMATIVE"}
extra = collections.defaultdict(list)
for l in LABELS:
    if l["Label"] == "MISSING":
        extra[key(DOC, l["Unit"])].append(l["Target"])
# the missing target is an external unit with no entry in this manifest version: it stays unknown (never assumed Complete)
examples = {}
for l in LABELS:
    u = key(DOC, l["Unit"])
    o_seen, o_unk = closure(u, E, {}, set())
    x_seen, x_unk = closure(u, E, extra, skip)
    examples[l["Unit"] + " → " + (l["Target"].split("|")[1] if l["Target"] else "(sin arista)")] = {
        "Label": l["Label"], "Line": l["Line"], "Text": l["Text"], "Why": l["Why"],
        "Original": {"ClosureSize": len(o_seen), "Unknown": len(o_unk), "PremiseCredible": not o_unk},
        "ExperimentalCopy": {"ClosureSize": len(x_seen), "Unknown": len(x_unk), "PremiseCredible": not x_unk},
    }

# whole-Proposal candidate omissions: backticked 16.9 check names
CHECKS = ["Termination", "Handoff", "Authority", "Contract", "Identity", "Remote", "Scope", "CleanTree", "Ci", "Tests", "Trailer", "Routing",
          "FreeText", "Denials"]
text = open(V14, encoding="utf-8").read().split("\n")
head = None
hits = collections.Counter()
by_section = collections.defaultdict(set)
for n, line in enumerate(text, 1):
    m = re.match(r"^#{2,4} (\S+)", line)
    if m:
        head = m.group(1).rstrip(".")
        continue
    for c in CHECKS:
        if re.search(r"`%s`" % c, line):
            hits[c] += 1
            by_section[head].add(c)
has_169_unit = any(e["Source"]["Document"] == AP and e["Source"]["UnitId"].startswith("16.9") for e in M["Entries"])
complete_flips = 0  # nothing in this script sets Complete; recorded for the record
result = {
    "Label": "EXPERIMENTAL — NOT AUTHORIZED FOR PRODUCTION",
    "Script": "b11_precision.py",
    "Manifest": {"Schema": M["Schema"], "AuthorityRevision": M["AuthorityRevision"], "Entries": len(M["Entries"]),
                 "Edges": sum(len(e["DependsOn"]) for e in M["Entries"])},
    "Examples": examples,
    "CandidateOmissions16_9": {"ManifestHasAUnitFor16_9": has_169_unit, "LinesNamingACheck": sum(hits.values()), "ByCheck": dict(hits.most_common()),
                               "SectionsWithMentions": len(by_section), "Note": "aproximado por sección; cada mención es candidata, no una arista confirmada"},
    "CompleteFlippedToTrue": complete_flips,
    "Checks": {
        "ExcessEdgesShrinkClosures": all(examples[k]["ExperimentalCopy"]["ClosureSize"] < examples[k]["Original"]["ClosureSize"]
                                        for k in examples if examples[k]["Label"] == "INFORMATIVE"),
        "ControlEdgesKept": all(examples[k]["ExperimentalCopy"]["ClosureSize"] == examples[k]["Original"]["ClosureSize"]
                                for k in examples if examples[k]["Label"] == "CONTROL"),
        "AmbiguityStaysUnknown": all(not examples[k]["ExperimentalCopy"]["PremiseCredible"] for k in examples if examples[k]["Label"] == "AMBIGUOUS"),
        "MissingEdgeWasCreditedAndBecomesUnknown": all(examples[k]["Original"]["PremiseCredible"] and not examples[k]["ExperimentalCopy"]["PremiseCredible"]
                                                       for k in examples if examples[k]["Label"] == "MISSING"),
    },
}
result["AllAsExpected"] = all(result["Checks"].values()) and complete_flips == 0
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    json.dump(result, f, ensure_ascii=False, indent=1)
    f.write("\n")
for k, v in examples.items():
    print("%-40s %-11s orig %3d/%d cred=%s  copy %3d/%d cred=%s" % (k, v["Label"], v["Original"]["ClosureSize"], v["Original"]["Unknown"], v["Original"]["PremiseCredible"],
                                                                   v["ExperimentalCopy"]["ClosureSize"], v["ExperimentalCopy"]["Unknown"], v["ExperimentalCopy"]["PremiseCredible"]))
print(result["CandidateOmissions16_9"])
print(result["Checks"], "all", result["AllAsExpected"])
